name: freezed_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
# freezed
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
# freezed
  freezed: ^2.4.1 
  build_runner: ^2.4.15
  json_serializable: 6.9.4


flutter:
  uses-material-design: true
  assets:
    - assets/sample.json